#pagebreak()
= Conclusion

Ce travail a appliqué le modèle de Fama-French à cinq facteurs aux rendements journaliers excédentaires de Microsoft (MSFT) sur la période janvier 2021 – décembre 2025 (T = 1 253 observations). L'estimation MCO du modèle FF5 produit un R² ajusté de 0,679, soit un gain de 12,16 points de pourcentage par rapport au CAPM (Adj.R² = 0,557). Les cinq chargements factoriels sont significatifs à α = 0,01 et cohérents avec le profil fondamental de MSFT : risque systématique légèrement supérieur au marché (β_mkt = 1,041), exposition aux grandes capitalisations (β_smb = −0,322), profil de croissance (β_hml = −0,379), forte rentabilité (β_rmw = +0,330) et stratégie d'investissement agressive (β_cma = −0,265). L'intercept alpha n'est pas significatif (p = 0,76), résultat cohérent avec l'hypothèse d'efficience des marchés : MSFT ne génère pas de rendement anormal au-delà de son exposition aux facteurs de risque systématiques.

La vérification des hypothèses de Gauss-Markov confirme la validité des estimateurs MCO. L'hypothèse de normalité des résidus (H2) est rejetée en raison de queues épaisses, caractéristiques bien documentées des rendements financiers journaliers ; le théorème central limite garantit néanmoins la normalité asymptotique des estimateurs pour n = 1 253, de sorte que l'inférence demeure valide. Les hypothèses d'homoscédasticité (H3) et d'absence d'autocorrélation (H4) ne sont pas rejetées à α = 0,01 par l'ensemble des tests appliqués. Les corrections présentées en section 7 sont purement pédagogiques : les conditions de Gauss-Markov sont satisfaites et les MCO restent les estimateurs BLUE.

Cette analyse comporte plusieurs limites à prendre en compte. La fréquence journalière amplifie la non-normalité des résidus par rapport à une fréquence mensuelle, bien que le nombre d'observations compense cet effet via le TCL. La période 2021–2025 couvre des régimes macroéconomiques très contrastés (reprise post-COVID, cycle de hausse des taux de 2022–2023, et essor de l'intelligence artificielle) qui peuvent affecter la stabilité des chargements factoriels dans le temps. Enfin, la comparaison avec les pairs (AAPL, GOOGL, META) est présentée à titre illustratif et ne constitue pas une analyse complète.

Une prolongation naturelle de ce travail consisterait à examiner la stabilité des chargements factoriels sur des sous-périodes glissantes afin de tester si les expositions de MSFT aux facteurs SMB, HML, RMW et CMA ont évolué avec la transformation du profil stratégique de l'entreprise.
